name: hanpanting

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hanpanting:ubuntu24.04
    container_name: hanpanting
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    volumes:
      - type: bind
        source: ${MONGODB_DATA_PATH}
        target: /var/lib/mongodb
